db:
  image: postgres:10
  ports:
    - "54322:5432"
  env_file:
    - ./docker-compose.env
web:
  build: .
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
notebook:
  # build: notebook
  image: rubydata/datascience-notebook
  volumes:
    - ./notebook:/home/jovyan/work
  ports:
    - "8888:8888"
  env_file:
    - ./docker-compose.env
  links:
    - db
  command: "start-notebook.sh \
    --NotebookApp.password=sha1:f9c9756ad0f9:fac50da3912b54df56e635823af7460b7c0304fc"
